on: [push]

name: "CI Node"

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [20]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}

      - name: NPM Install
        working-directory: ./ui
        run: npm install

      - name: Lint, build/export
        working-directory: ./ui
        run: |
          npm run lint
          npm run export



